[bar.default]
center = [ "clock", "cat" ]
font_family = "JetBrainsMono Nerd Font Mono"

[lockscreen]
wallpaper = "/home/dhalytskyi/dotfiles/wallpapers/catppuccin/mocha/kurzgesagt/Cloudy_Quasar_1-Catppuccin_Mocha.png"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@Virtual-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@Virtual-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 640.0
    cy = 618.0
    output = "Virtual-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@Virtual-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugins]
enabled = [ "noctalia/bitwarden", "noctalia/bongocat", "noctalia/timer" ]

[shell]
font_family = "JetBrainsMono Nerd Font Mono"
settings_show_advanced = false

[theme]
builtin = "Tokyo-Night"
community_palette = "Oxocarbon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-content"

[wallpaper]
directory = "/home/dhalytskyi/dotfiles/wallpapers/catppuccin/mocha/kurzgesagt"

    [wallpaper.default]
    path = "/home/dhalytskyi/dotfiles/wallpapers/catppuccin/mocha/kurzgesagt/Cloudy_Quasar_1-Catppuccin_Mocha.png"

    [wallpaper.last]
    path = "/home/dhalytskyi/dotfiles/wallpapers/catppuccin/mocha/kurzgesagt/Cloudy_Quasar_1-Catppuccin_Mocha.png"

    [wallpaper.monitors.Virtual-1]
    path = "/home/dhalytskyi/dotfiles/wallpapers/catppuccin/mocha/kurzgesagt/Cloudy_Quasar_1-Catppuccin_Mocha.png"

    [[wallpaper.favorite]]
    builtin_palette = "Catppuccin"
    palette_source = "builtin"
    path = "/home/dhalytskyi/dotfiles/wallpapers/catppuccin/mocha/kurzgesagt/Cloudy_Quasar_1-Catppuccin_Mocha.png"
    theme_mode = "dark"

    [[wallpaper.favorite]]
    path = "/home/dhalytskyi/dotfiles/wallpapers/catppuccin/mocha/kurzgesagt/Cloudy_Quasar_2-Catppuccin_Mocha.png"
    theme_mode = "auto"

[widget.cat]
type = "noctalia/bongocat:cat"

[widget.logo]
font_family = "JetBrainsMono Nerd Font Mono"
